In [3]:
import numpy as np

def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.tanh(x)**2


X = np.array([[-0.2, 0.2],
              [0.3, 0.4],
              [-0.1, -0.5]])

y = np.array([[0.45],
              [0.6],
              [0.35]])

weights_1 = np.random.random((2, 3)) - 0.5
weights_2 = np.random.random((3, 3)) - 0.5
weights_3 = np.random.random((3, 1)) - 0.5

result_error = 0;

num_iterations = 10000

for i in range(num_iterations):

    layer_1 = tanh(np.dot(X, weights_1))
    layer_2 = tanh(np.dot(layer_1, weights_2))
    layer_3 = tanh(np.dot(layer_2, weights_3))


    error = y - layer_3

    layer_3_gradient = error * tanh_derivative(layer_3)
    layer_2_gradient = layer_3_gradient.dot(weights_3.T) * tanh_derivative(layer_2)
    layer_1_gradient = layer_2_gradient.dot(weights_2.T) * tanh_derivative(layer_1)

    weights_3 += layer_2.T.dot(layer_3_gradient)
    weights_2 += layer_1.T.dot(layer_2_gradient)
    weights_1 += X.T.dot(layer_1_gradient)

    result_error = error
    
print("")

print("------Досягнуте значення помилки-----")

print(result_error)
print("")

print("Порівняння виходів (у) та вихідних данних за результатами навчання (layer_3)")
print(y)
print(layer_3)


------Досягнуте значення помилки-----
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.11022302e-16]]

Порівняння виходів (у) та вихідних данних за результатами навчання (layer_3)
[[0.45]
 [0.6 ]
 [0.35]]
[[0.45]
 [0.6 ]
 [0.35]]
